version: 2
registries:
  npm-registry-npm-dev-bonuz-com:
    type: npm-registry
    url: https://npm-dev.bonuz.com/
    username: "${{secrets.NPM_REGISTRY_NPM_DEV_BONUZ_COM_USERNAME}}"
    password: "${{secrets.NPM_REGISTRY_NPM_DEV_BONUZ_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.3.3
  registries:
  - npm-registry-npm-dev-bonuz-com
